[package]
name = "userspace_hub"
version = "0.2.3"
edition = "2024"
authors = ["José Gois <ze.gois.00@gmail.com>"]
description = "userspace_hub library"
documentation = "https://docs.rs/userspace_hub"
repository = "https://github.com/ze-gois/rust_userspace_hub"
readme = "README.md"
homepage = "https://userspace.party/hub"
license-file = "LICENSE"
keywords = ["architecture", "operating_system"]
categories = ["no-std", "os"]
publish = true
exclude = []
include = []
rust-version = "1.85"
autobins = true
autotests = true
autobenches = true
resolver = "2"
# license = "BSD-3 Clause"
# links = ""                    # se a crate linka C libs externas

[package.metadata]
mode = "unoticed"
note = "esta é uma crate padrão"
whatever = 42

[package.metadata.debug]
mode = "debug"

[workspace]
members = [
    "crates/ample",
    "crates/computers",
    "crates/humans",
    "crates/kernelspace",
    "crates/twins",
    "crates/userspace",
    "crates/userspace_build",
    "crates/webspace"
]

[patch.crates-io]
ample = { path = "crates/ample" }
computers = { path = "crates/computers" }
humans = { path = "crates/humans" }
kernelspace = { path = "crates/kernelspace" }
twins = { path = "crates/twins" }
userspace = { path = "crates/userspace" }
userspace_build = { path = "crates/userspace_build" }
webspace = { path = "crates/webspace" }

[lib]
name = "userspace_hub"
path = "src/library.rs"
crate-type = ["lib"]
test = false
doctest = true
bench = false
required-features = []        # nenhuma feature obrigatória
doc = true                     # gera docs

[[bin]]
name = "userspace_hub"
path = "src/entry.rs"

[dependencies]
ample = "0.2.3"
userspace = "0.2.3"
kernelspace = "0.2.3"
twins = "0.2.3"
humans = "0.2.3"
webspace = "0.2.3"
computers = "0.2.3"

[build-dependencies]
cc = "1.0"
userspace_build = { version = "0.2.3", features = ["with_std"] }

[dev-dependencies]

[features]
default = []
all = []

[badges]
github-actions = { repository = "ze-gois/rust_userspace_hub" }

[profile.dev]
opt-level = 0
debug = true
overflow-checks = true
lto = false
panic = "unwind"
incremental = true
codegen-units = 256
debug-assertions = true
split-debuginfo = "packed"

[profile.release]
opt-level = 3
debug = false
overflow-checks = true
lto = true
panic = "abort"
codegen-units = 1
incremental = false
debug-assertions = false
split-debuginfo = "unpacked"
rpath = false
strip = "debuginfo"
