[build]
target = "x86_64-unknown-none"

[unstable]
build-std = ["core", "alloc"]

[target.x86_64-unknown-none]
rustflags = [
    "-Z", "macro-backtrace",           # Debug de macros
    "-C", "relocation-model=static",  # Necessário pra bare-metal
    "-C", "code-model=small",          # Code model pequeno, adequado pra kernels simples
    "-C", "prefer-dynamic=no",         # Force linking estático
    "-C", "force-frame-pointers=yes",  # Mantém frame pointers para debug
]
