[build]
target = "x86_64-unknown-none"

[unstable]
build-std = ["core", "alloc"]
# build-std = ["core", "compiler_builtins"]
# build-std-features = ["compiler-builtins-mem"]

[target.x86_64-unknown-none]
rustflags = [
    "-Z",
    "macro-backtrace",
    # Use static relocation model for bare-metal
    "-C",
    "relocation-model=static",

    # Disable position-independent executables
    "-C",
    "code-model=small",

    # Prefer static linking
    "-C",
    "prefer-dynamic=no",

    # Pass linker script
    # "-C",
    # "link-arg=-T",
    # "-C",
    # "link-arg=linker.ld",

    # Additional flags for bare metal
    "-C",
    "force-frame-pointers=yes",
]


[alias]
xelf_std = "run -p xelf -Z build-std=std,core,compiler_builtins --features with_std"
xelf_no_std = "run -p xelf"
